**First part**

In [1]:
import sys
print(sys.executable)

import numpy as np
print(np.__version__)

d:\AI_Diploma_Master\ai_diploma_master\env\Scripts\python.exe
2.5.2


In [2]:
import numpy as np

def array_factory(mode, shape, value=None):
    """
    Creates various NumPy arrays based on the mode.

    - 'zeros': Array filled with 0.
    - 'ones': Array filled with 1.
    - 'full': Array filled with a specified value.
    - 'identity': A square identity matrix.
    """

    if mode == "zeros":
        return np.zeros(shape)

    elif mode == "ones":
        return np.ones(shape)

    elif mode == "full":
        return np.full(shape, value)

    elif mode == "identity":
        return np.eye(shape)

    else:
        return "Invalid mode"

In [3]:
print(array_factory("zeros", (2, 3)))
print(array_factory("ones", (2, 3)))
print(array_factory("full", (2, 2), 5))
print(array_factory("identity", 3))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**seconed part**

In [4]:
import numpy as np

def secure_reshape_and_stack(data1, data2, new_shape):
    """
    1. Validates and converts inputs to NumPy arrays.
    2. Reshapes the first dataset to a specific dimension.
    3. Vertically stacks both datasets into one matrix.
    """

    try:
        arr1 = np.array(data1)
        arr2 = np.array(data2)

        reshaped_arr1 = arr1.reshape(new_shape)

        combined_dataset = np.vstack((reshaped_arr1, arr2))

        return combined_dataset

    except ValueError as e:
        raise ValueError(f"Company-grade Error: {e}")

In [5]:
data1 = [1, 2, 3, 4, 5, 6]
data2 = [[7, 8, 9],
         [10, 11, 12]]

result = secure_reshape_and_stack(data1, data2, (2, 3))

print(result)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
